FROM ubuntu:18.04

RUN apt update \
    && apt install -y \
        software-properties-common \
        wget

RUN wget --quiet -O - https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - \
    && apt-add-repository 'deb https://deb.nodesource.com/node_10.x xenial main'
RUN apt update \
    && apt install -y nodejs

RUN rm -rf /var/lib/apt/lists/*
